/**
 * Emits `dist/_headers` (Netlify's per-path header file) after every build.
 *
 * Why generated instead of hard-coded in netlify.toml: the Content-Security-Policy
 * pins the SHA-256 of the inline pre-paint theme script from index.html. Computing
 * it from the *built* HTML means the hash can never go stale — edit the inline
 * script freely and the next build picks it up automatically.
 *
 * Side effect worth knowing: a script-src without 'unsafe-inline' also stops
 * Netlify's edge-injected "Powered by Netlify" badge from rendering, which is
 * documented behaviour, not a workaround.
 * https://docs.netlify.com/manage/projects/powered-by-netlify-badge/
 */
import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const dist = join(root, 'dist')
const html = readFileSync(join(dist, 'index.html'), 'utf8')

/** Hash every inline <script> (those without a src) so the CSP allows exactly ours. */
const inlineScripts = [...html.matchAll(/<script(?![^>]*\ssrc=)[^>]*>([\s\S]*?)<\/script>/g)].map((m) => m[1])
const hashes = inlineScripts.map((body) => `'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`)

if (!hashes.length) {
  console.warn('[headers] no inline scripts found in dist/index.html — check the build output')
}

// Remote origins the app genuinely talks to. Keep this list minimal and explicit.
const GITHUB_API = 'https://api.github.com'
const CONTRIB_API = 'https://github-contributions-api.jogruber.de'
const GITHUB_AVATARS = 'https://avatars.githubusercontent.com'

const csp = [
  `default-src 'self'`,
  // No 'unsafe-inline': only our own hashed bootstrap script may run inline.
  `script-src 'self' ${hashes.join(' ')}`.trim(),
  // React and Motion write element style attributes at runtime, so inline styles must stay allowed.
  `style-src 'self' 'unsafe-inline'`,
  `img-src 'self' data: blob: ${GITHUB_AVATARS}`,
  // Vite inlines the small cyrillic-ext font subsets as data: URIs, so they must be allowed.
  `font-src 'self' data:`,
  `connect-src 'self' ${GITHUB_API} ${CONTRIB_API}`,
  `worker-src 'self' blob:`,
  `manifest-src 'self'`,
  `object-src 'none'`,
  `base-uri 'self'`,
  `form-action 'self'`,
  `frame-ancestors 'none'`,
  `upgrade-insecure-requests`,
].join('; ')

const body = `# Generated by scripts/generate-headers.mjs — do not edit by hand.

/*
  Content-Security-Policy: ${csp}
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  X-Frame-Options: DENY
  Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), microphone=(), payment=(), usb=()
  Cross-Origin-Opener-Policy: same-origin

# Vite emits content-hashed filenames, so these are safe to cache forever.
/assets/*
  Cache-Control: public, max-age=31536000, immutable

# HTML must always revalidate so a new deploy is picked up immediately.
/
  Cache-Control: public, max-age=0, must-revalidate

/index.html
  Cache-Control: public, max-age=0, must-revalidate
`

writeFileSync(join(dist, '_headers'), body, 'utf8')
console.log(`[headers] wrote dist/_headers (${hashes.length} inline script hash${hashes.length === 1 ? '' : 'es'} pinned)`)
